name: Frontend Build and Test

on:
  push:
    branches:
      - main

jobs:
  defaults:
    run:
      working-directory: frontend

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests (if applicable)
        run: npm test

      - name: npm CI
        run: npm ci

      - name: Lint
        run: npm run lint
