name: Backend Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Use Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check versions
        run: |
          python --version
          pip list

      - name: Lint with flake8
        run: |
          flake8 -v --count --select=E9,F63,F7,F82 --show-source --statistics backend/
          flake8 -v --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics backend/

      - name: Lint with pylint
        run: |
          pylint $(find . -iname "*.py") --fail-under=9.0
