name: Backend Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Check versions
        run: |
          python --version
          pip list

      - name: Lint with flake8
        run: docker compose run --rm backend sh -c "flake8"

      - name: Test
        run: docker compose run --rm backend sh -c "python peak/manage.py test"
